### ISSUE TITLE
怎么我会收到Actions的邮件

### ISSUE THREAD

**Issue by simon300000** [laosepi/setu#4]
是什么点了star导致的吗？
<img width="494" alt="image" src="https://user-images.githubusercontent.com/12656264/98262938-79888180-1f86-11eb-9c36-cf9f770214fc.png">

**Comment by zhihaofans** [comment]
你点了watching？

**Comment by simon300000** [comment]
没有啊

**Comment by yuban10703** [comment]
因为你点了start,然后启动了action...

**Comment by simon300000** [comment]
那看起来还真是因为点了star

**Comment by simon300000** [comment]
y1s1 repo 好活
